version: "3.3"
services:
  app-counter:
    build: .
    ports:
      - 80:8000
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    restart: always
    networks:
      - redis-net

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data/redis:/data
      - ./redis/config/redis.conf:/redis.conf
    command: redis-server /redis.conf --requirepass thisispassword
    networks:
      - redis-net

  redis-mgmt:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=thisispassword
    ports:
      - 8081:8081
    restart: always
    networks:
      - redis-net

networks:
  redis-net:
